### ISSUE TITLE
Automatic dropdown on details in  navbar

### ISSUE THREAD

**Issue by LavishRawat** [Sachinbisht27/Project_1#31]
On the main page , add a feature so that when someone hover over details in navbar the dropdown automatically  show the list.

**Comment by ThorezNS** [comment]
Hey I would like to work on it

**Comment by tarunnjoshi** [comment]
> Hey I would like to work on it

Wait we talk to our team.

**Comment by LavishRawat** [comment]
Yes , u can clone the repo and start working on this issue .You can Push the code when the task is completed.

> Hey I would like to work on it

**Comment by LavishRawat** [comment]
> Yes , u can clone the repo and start working on this issue .You can Push the code when the task is completed.
> 
> > Hey I would like to work on it

https://discord.gg/aktzJ6ny Here's the discord link , if you want to Join.
